# Generated by Django 3.2.18 on 2023-03-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
